### ISSUE TITLE
Tutorials: Ambisonic Toolkit for Reaper

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/ambisonictoolkit.github.io#18]
Consider either directly linking to the [DXARTS](https://dxarts.washington.edu/) Wiki page [Ambisonic Mixing in Reaper](https://dxarts.washington.edu/wiki/ambisonic-mixing-reaper), or make a new page based on this, to be made available at / from [Tutorials: Ambisonic Toolkit for Reaper](http://www.ambisonictoolkit.net/documentation/reaper/tutorials/).

There is a limitation with the current DXARTS page [Ambisonic Mixing in Reaper](https://dxarts.washington.edu/wiki/ambisonic-mixing-reaper). These instructions are for setting up a session where the output B-format is passed to an external decoder.

We would expect the average atk-reaper user would be using an atk decoder within their Reaper session. This being the case, a new page hosted at www.ambisonictoolkit.net would likely be more useful. In any case, the DXARTS [page](https://dxarts.washington.edu/wiki/ambisonic-mixing-reaper) _is_ very good with details about setting up and getting started.

**Comment by joslloand** [comment]
This is related to [Add useful track templates to Reaper #23](https://github.com/ambisonictoolkit/atk-reaper/issues/23).

**Comment by mtmccrea** [comment]
> There is a limitation with the current DXARTS page Ambisonic Mixing in Reaper. These instructions are for setting up a session where the output B-format is passed to an external decoder.

I had a quick look at my tutorial, and it does cover [decoder tracks](https://dxarts.washington.edu/wiki/ambisonic-mixing-reaper#decoder-tracks), though it's down the page, after the discussion of Folders.  The relevant info there is:

> If your FOA or HOA mix is bussed through a "B-format Master" Folder track, you can add track sends from this Folder track to one or more tracks that have decoders in their FX chain. This has many advantages: 
> 
> These decoder tracks would send to the hardware outputs according to their type of decoding. For example, 
> a UHJ decode may be set to stereo speakers
> an HRTF decode may be sent to headphone outputs from the audio interface
> a 5.1 decode may get sent to a 5.1 surround system
> the TOA mix may be sent to a dedicated decoding system run on another computer or piece of hardware
> Each decoder track could be muted, solo'ed, and have levels adjusted independently.
> Additionally, each decoder track can be selected for (stem) rendering to a desired output format, without changing the core routing setup of the session. Read on for instrunctions on how to render your mix.

To make note of decoder routing earlier in the tutorial, I updated the first section, [Hardware Routing](https://dxarts.washington.edu/wiki/ambisonic-mixing-reaper#hw-routing) to make mention of decoder routing and link to the Folders and Decoder Tracks sections.

**Comment by joslloand** [comment]
Ok, thanks for the update.

Do we think this would be ready to add a link to the [DXARTS page](https://dxarts.washington.edu/wiki/ambisonic-mixing-reaper) on [Tutorials: Ambisonic Toolkit for Reaper](http://www.ambisonictoolkit.net/documentation/reaper/tutorials/)?

**Comment by mtmccrea** [comment]
Added. We can re-open or start a new issue if we decide to port the content to live on the ATK site (it would take some work, given the images and many anchors in the page).
