### ISSUE TITLE
Include atk-sc3 Help

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/ambisonictoolkit.github.io#29]
With the removal of schelp files from [sc3-plugins](https://github.com/supercollider/sc3-plugins), atk-sc3's help no longer appears at http://doc.sccode.org/.

As a result, the atk-sc3 help on the ATK web page is no longer available at:

http://www.ambisonictoolkit.net/documentation/supercollider/

Will need to review using [SCDoc](http://doc.sccode.org/Classes/SCDoc.html) to render help pages to include on the ATK site.

**Comment by joslloand** [comment]
## Further notes

We initially considered the problem of online Help with the very first release of the ATK. The original thread started by @joshpar on the sc-dev mailing list is titled [online Help](http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/online-Help-td7372305.html).

Jonatan Liljedahl's (aka @lijon) advice on Mar 14, 2012 was:

> http://doc.sccode.org/ has the whole help online, but it does not include any quarks etc.. 
> 
> You should be able to just copy the rendered ATK help html files from your local helpTargetDir and put them on a server. The links should already be relative, except links to .sc source files etc.. and the Home,Browse,Search links expect their files in correct place, etc, also they need scdoc.js and friends, so you should copy the whole Help dir and just remove/replace the files you don't need. 
> 

@vividsnow (aka [vividsnow](http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/template/NamlServlet.jtp?macro=user_nodes&user=341642)) is the maintainer of http://sccode.org/.

Conveniently, http://doc.sccode.org/ includes help docs for [supercollider/sc3-plugins](https://github.com/supercollider/sc3-plugins). Linking directly to http://doc.sccode.org/Guides/Intro-to-the-ATK.html has worked when the ATK's help files were part of [supercollider/sc3-plugins](https://github.com/supercollider/sc3-plugins). However, in the move to atk-sc3 as a Quark, this functionality is now lost.

Some possible options include:

1. Host @ http://doc.sccode.org/
We'd need to contact @vividsnow and request installation of the atk-sc3 Quark on the http://sccode.org/ host site. While possibly convenient, this _isn't necessarily the best solution_. In particular, we'd be asking the maintainer to do us a favor. Also, as the ATK documentation is updated, the latest documentation would not necessarily be up to date.

2. Host @ [ambisonictoolkit/ambisonictoolkit.github.io](https://github.com/ambisonictoolkit/ambisonictoolkit.github.io)
I've looked into this (along with @mtmccrea), and haven't had much luck. In following @lijon's advice above, when the complete `Help` directory of rendered .html files is dropped into the repository `ambisonictoolkit.github.io`, the local [Jekyll](https://jekyllrb.com/) server fails to start. (See the Terminal trace below.) Note, `realpath_rec` is a [Ruby](https://www.ruby-lang.org/en/) variable.

```
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.5.2 | Error:  No such file or directory @ realpath_rec - /Users/admin
```
3. Host @ _some other site_
This could possibly be http://realizedsound.net/ or even the [DXARTS Wiki](https://dxarts.washington.edu/wiki/tutorials#atk). There is an argument to be made that hosting at [DXARTS Wiki](https://dxarts.washington.edu/wiki/tutorials#atk) would make sense for teaching

4. Do nothing...
I.e., sunset online documentation for atk-sc3.

### Discussion

My preferred solution would be 2. Host @ [ambisonictoolkit/ambisonictoolkit.github.io](https://github.com/ambisonictoolkit/ambisonictoolkit.github.io). The release cycle would then be through GitHub. I.e., everything would happen in one place. Integrating [Jekyll](https://jekyllrb.com/) and the generated `Help` directory of rendered .html files does not immediately appear to be trivial. (We'd probably need someone with a deeper understanding of [Jekyll](https://jekyllrb.com/) and HTML to make that happen.)

Option 3. Host @ _some other site_ is probably the most likely solution for the short term. There may be similar challenges to 2., but the thought is that the `SCDoc` generated HTML would be easier to integrate with other hosts.

**Comment by joslloand** [comment]
Option 3:

6841a18fbe3b74a1d9a019ef6afe9f22f972e224

Local copy online at: http://depts.washington.edu/dxscdoc/Help/Help.html

Thanks @trebacze!

**Comment by vivid-synth** [comment]
FYI I am not the same person as vividsnow. An unfortunate name similarity! I believe the person you're looking for is @vividsnow

**Comment by joslloand** [comment]
Apologies for the mistake, @vivid-synth! I've updated the comment above.
