### ISSUE TITLE
SuperCollider doc iframe gives a 404

### ISSUE THREAD

**Issue by lossius** [ambisonictoolkit/ambisonictoolkit.github.io#3]
The iframe with embedded SuperCollider documentation at this page gives a 404:

http://www.ambisonictoolkit.net/documentation/supercollider/

This is expected behavior as the URL at line 12 of documentation/sc3.md points to http://www.ambisonictoolkit.net:

```
http://www.ambisonictoolkit.net/Help/Guides/Intro-to-the-ATK.html
```

This URL now gets redirected back to github.io, where these files do not exist. I suppose we need to find another location for hosting the documentation and update the URL accordingly.

**Comment by joslloand** [comment]
The immediate solution is to repoint to the ATK help pages that are automatically built as part of the [sc-plugins extension set](https://github.com/supercollider/sc3-plugins).

Docs found here: [http://doc.sccode.org/Guides/Intro-to-the-ATK.html](url)

In the (nearish-)long term, @scztt and @mtmccrea are looking to move SC3-ATK to a [Quark](https://github.com/supercollider-quarks/quarks) repository. When that happens, we'll _probably_ need to redirect SC3 documentation to the Quark location.
