### ISSUE TITLE
supercollider atk works on win also

### ISSUE THREAD

**Issue by sonoro1234** [ambisonictoolkit/ambisonictoolkit.github.io#4]

**Comment by lossius** [comment]
Thanks, @sonoro1234 for reporting. 

@joslloand : This report is probably relating to the information in the blue info frame on this page:

http://www.ambisonictoolkit.net/download/supercollider/

Seems like it should be updated?

**Comment by sonoro1234** [comment]
@lossius also in http://www.ambisonictoolkit.net/
down-right

**Comment by joslloand** [comment]
Closed with https://github.com/ambisonictoolkit/ambisonictoolkit.github.io/pull/6
